#!/bin/bash


## Load the required modules
module load mpt
module load intel-compilers-19

## compile


## compile with MPI:
mpicxx matmul_gen.cpp  -o MatMulPerExe

## remove object files if there is any!:
# rm *.mod
# rm *.o

